In [3]:
import numpy as np
import nearpy as nearpy

In [5]:
from nearpy import Engine
from nearpy.hashes import RandomBinaryProjections

In [10]:
class HashFunction():
    def __init__(self,dim,k,l):
        self.dim=dim
        self.k=k
        self.l=l

In [33]:
class NearPyHash(HashFunction):
    def __init__(self,dim,k,l):
        super(NearPyHash,self).__init__(dim,k,l)
        lshashes=[RandomBinaryProjections('hash_{}'.format(i), 10) for i in range(k)]
        for lsh in lshashes:
            lsh.reset(dim)
        self.engine=Engine(dim, lshashes=lshashes)
        
    

In [34]:
nrp=NearPyHash(4,5,6)

In [22]:
for index in range(1000):
    v = np.random.randn(4)
    nrp.engine.store_vector(v, 'data_%d' % index)

In [24]:
nrp.engine.neighbours(np.random.randn(4))

[(array([ 0.52016089,  0.64716816, -0.52113539,  0.19754473]),
  'data_328',
  0.008680095313714054),
 (array([ 0.51710797,  0.39318482, -0.75572984,  0.08293036]),
  'data_596',
  0.029439589496146223),
 (array([ 0.60668164,  0.33677226, -0.68229227,  0.23021532]),
  'data_720',
  0.03593083553003096),
 (array([ 0.58029109,  0.31814927, -0.7335266 ,  0.15486129]),
  'data_718',
  0.04059250919369717),
 (array([ 0.6393096 ,  0.47086876, -0.57115431, -0.20820327]),
  'data_200',
  0.06744518793639875),
 (array([ 0.76200742,  0.3499317 , -0.45103671,  0.30570965]),
  'data_230',
  0.07066488185274478),
 (array([ 0.54613776,  0.41379371, -0.54514318,  0.48303956]),
  'data_266',
  0.07362732839790043),
 (array([ 0.68454972,  0.37473353, -0.45119341,  0.4328868 ]),
  'data_556',
  0.08217401403691571),
 (array([ 0.34321795,  0.85988317, -0.36248702,  0.10679673]),
  'data_232',
  0.0929631189055179),
 (array([ 0.54677407,  0.24831921, -0.6674019 ,  0.44039798]),
  'data_485',
  0.099654188

In [31]:
rbp=RandomBinaryProjections('default', 10)
rbp.reset(5)

In [32]:
rbp.hash_vector(np.random.randn(5))

['0000100000']